language: go
env:
  GO111MODULE=on #no se toca
deploy:
  provider: heroku
  api_key:
    secure: "LyR3hm4/8bJtbcMWYILUaHjiu4cvoCboCOho2QBR4TNGkjy67TeI7oBRMzGmU9+okxFs52mXZVL7GBWzlkUZrx0c+q6mvMAydmrvqxTcuYt07A/DXezg66JKdpHblpGXNRAOjzQnW8ApFJKw677lVr3yiX9aqPa24T/SzLEbU5jU5zkmcLTNuKYqg6En8C2bUhjVVgGgRB0Mq1ABxCKMkqUk60WmVpMtu0jMBKKxYw6/RzXaNVqKP/EPirhWejLuE0vclfYnLALyfUFP5FYYO+l8pXBO9zDCrlXQLu0ZS5bEGM3sSU1HtXla63Tt9j38nbrxDgqseLhyid2Hi/KeckRezYx3eqnI+WInQSCYqeXUOXTUwQn5/8WoaSPNsi3s74Amgsm9qWbwYimRuCsA3numeEtHyqBM+V7CNyfjHPxnL7NbIBmehmNz+vOQT1xHUHRfQDRGxk6ZJVWuGhyLxkTaByYhbPqD0j/+eJdJrPnYGcZ8Z4UNg8m1oN+FOa+OGETnTrp26cSZXfLP7fx1ckeJMzjMP5T7cQziEpyg2dw40e/AXfHODRnJwD6V0Dk+YpMzcfxXUfAB/JB1rnIkb2Nemd6vMS9o8WgagTFs0c/0xoYDpxJvx8FLNgZXuLCZyY/4nZ/JNtsfDi0SrwZalZyCfSK6G+0WSAgfR8gYCt4="
