language: go
env:
  GO111MODULE=on #no se toca
deploy:
  provider: heroku
  api_key:
    secure: "EdXhJ9cERwlc+zRO8z3irIclF4VMsH/uepR+kT0Wz5YLgZF48kAAiPvc+VMAFOyk3kd9y7rMfJopMk2ozzS7/Gy7OeKoPX2YyVrg9bhPg48HegDHyLJrigPvCBIKqWOyNxKzi9XExlOdS3AlZK/CbbUOeMjunnxNeoTonsetmMKmMlM1ct3t43gAEcpo+zOLwNzO8bNatZ9OlPImpuJZZ2aLtjfnpJCbwUGJR1eyu5tDpDqsi+4KeDqNJk2q8fQkvjCX5TjBkkmQPlDF0lhznKIPBMyesX0PoQUqhPDzAZjavMIX2rSv1u87x6OYlCK3fmZpwol0BTnIIdPmxlPGBrlssUFRWheB+/5HRetlqb14pE2gQ3i2F58TY9RznSV48dvVHrTKfkOFvxCEGSPLlfUZAgrwAq12waYukOtyRbp/b8wmqmuRXsM6zRlelN7MksCR4e/YB30Q7fUwqkLACzSkGaUdu2q3L0U/HGEXLrV5gEr/+JQ43/bMrvl+H9zjfObwQKRlFoavLw3xh46pNbz/w4XfnccfTKsOIrVP9JyGU1JfeCPPTZ5kRaUyX1tb2H2HGG7/c3+CNKT8iP/HmrzN7Q7CgELdrxrn64Rx3bBEEpYENEgoz338A9gSyf/ehwheFo599RsNmKWJQkhO0hOx+fS7LZ+DE9qfitGKbLg="
  app:
  	master: golang-pokemon-api
