language: go
env:
  GO111MODULE=on #no se toca
deploy:
  provider: heroku
  api_key:
    secure: "A9HcdM0bMLNwucma+XF3GrO+wcxckHbFeOyHhTwNDPkaQgz8gVvpcWEhYTs3uAN8oBqu5aNQm5ljRXX/W2luqKFYGcojYwsvpNSckBMmnwz0YL49K0E/CI3+DjtQoklEDz/G8Khqhgg56W9NRcUhbPKYhGozy2Do/nhFySNon71JVKRfZLtWnR4t+JXuaScAPAiDShZTazf6I2RAeYntSFGfIuhpfsFn6K5r+d9TUvZPD/enEb716KGzEUgYRxivYWyvE1W5v2Kex1LpLjA+ywaptrwlV1vK321WvuZatzJJkHH5ciFPQA7pCAk8O/5cH7xM/ix6aFlF7L3fiNXgIfXLGNorAg8aoyWZaQkyHcPKbalouXnabqd5u9HYIhW8R1nNRKSAvif8lQ4//+OaUwsjZnJiEsU/wlDzxJVZeN6eCkk89ERmqnwz+x67IFtBcq56RAHWCsPwVpVuI93qFI+rIAiWrGUGClrPXmEodQBDsYwqge7vFyy09KMVOAgKj74SGfnmpis202vOBH24fAPQbfCMVEQM7RAq74YginwE85NmCLV371EqNwqYNf13sNJH5qOlEFDJ4FhhwOFVWRSae/Wdm+oVZVa5gXRgHON221G4h3tVO3C9KEvUSySSipBvl10YG8vkN2gSCONzQDEEgMfgN4eIDKEwmJgnJlA="
  app:
  	master: golang-pokemon-api
