language: go
env:
  GO111MODULE=on #no se toca
deploy:
  provider: heroku
  api_key:
    secure: "SYndI4E7HbTb4MOWVCTq2M8Mn+AO+CjCLW3QIhX/Te1DKJNQ9LyvKA1xZAdNuncS2mCoQ39CX+jqhw4lkeE/KcY0K6jbHM8XnD9fTcBrTonOp1KmBSlTIxjWpfDYNnckTdxb9lNHescxlbMRtTC/LNOsucSzn/GFdqlCCiO7E35WTq038VxxmSBNmUhw9ESszq83fD190kgcCBNeeGiWXsC92i/ZQJ1s+3F94vHHoA7g4s/IPWd08M5hzItBC6k6/0rvEfMNocyBVmCug1BtRfs/BWmgtncHPhpj+FMLxSzRZsEA/R9oz64wT+uaBzhvwngUWpCq2ub9mUQzPPp1ahAtGDjMh9sIxoSOI09j1fWNzJ7N8uj2Yrgz8Q0PhGtHRVUPW4s46ptsSQzYC55mN+dOLQbMPWzTqJo1J72F08cwOghD6gu7/WAgnr3PF4PE0AYGDv/QmqEWjgFSaA4EX1oaR8Tx/tH5/e+NS/zp/OUhslUvfgEESalMX9g4z0X5I1kJhEA7nMYAWNOe+iFl5gDuQ9zi3698ou6S+trlgWf5nI5+NzdylL0XdjyId9qAiYJ6QPTXtzTFfV9WmvTiAkiHHqobbreS5nHo6/piAA0sOx8BWtMmJMwcfcmL1pCmqAjF+n5juZVn5d6BfS9WlOE0YSIdpuD5G3deAGxHPA8="
  app:
    master: golang-pokemon-ap
  sonarcloud:
    organization: "daval03"
    token:
      secure: "kvTZRjET1GisPgp18ws6yAr84P+eMHX3pboE1a3ZJ2jxGUW++Yks7EbVtGFRTjmRatMfspml1QZLlyxR7p95Vonez1cY9heXnbeuCAnePWMeda3pKOm4a62cwBWBuFQN1Tyz1frXboDG3molJs5ogpA872nv8p/5OUZBRl5o0b/479uzzjp5zQ0Vuj1yTBoY73OFKSJ9aqT8Aa/uSguKprjdl7wKNjrk6cCbPfxxLbdpX4H2uVTkY3slkPzJ4O/yAFB84Rj9Tac1d/Vv1FnXAGdXK7LLvzGz3ijxWGKY9ambK11wInRO67vWOf2h6slTozAmqQI88P8HWbKS84rJA0IQ83Qt1A/G5kw5B0q7ec4eJqUZx7fp+9o4vep+vYXhieVJdzFzVabjF+9CNqNotKn6+KjwlreFsqZ4P3+QQOAFaqpOzXGtGJvILvUR1NfKwl2cmTx5sgSGOLNCGVnyY1oderGjrG0/3+Oxk3Q/IRvrreP9JD7y5lvmk9pUvFCV5Kfqt+B7cBoj5ZvcveywxXwG5h+thQ9JLEo7yojWqSc9Q7Y0PPbigbasFdRjm7z92y4d5kQDRG9Pz697NUibLvIOXzXCzi/qEuuhCNo2i696bm+jXrY8p3b/Qv+OD4IbRmf2T/nnj+HtYqgpDG0P7f83DQzt+SyfJsDDs0gfnaA="
script:
  - sonar-scanner
